(define count-down (lambda (x) 
    (let ((y (if (eq? x 0) x (count-down (- x 1)))))
	y)))
(define (cd1) (count-down 1000))
(define tc "Repl.TestClass, Repl")
(define x (method "TestMethod1" tc))
(define y (method "TestMethod2" tc))
(define c (new tc))

(p "loaded")
