
(define test1 (lambda () 
(let ((x '(1 3 5 7 9))
      (sum 0))
     	       (do ((x x (cdr x)))
    		       ((null? x))
    		      (set! sum (+ sum (car x))))
    	       sum)))
(test1)
(p "loaded")
